feat: landing page design refresh
jenkins-infra/stats.jenkins.io pull request #63
Opened 2024-06-27 20:46 UTC by shlomomdahan

Before:
![Screenshot 2024-06-27 at 4 45 45 PM](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/58d226db-c803-4fd2-85ba-093bf7dcf3db)

After: 
![Screenshot 2024-06-27 at 4 45 10 PM](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/b3aed6f7-e952-43c0-89b2-091b9eaf0da1)

2024-06-28 07:57 UTC, lemeurherve commented
I'm not sure this is a good change, we're loosing affordance of the buttons, nothing indicate that each of these lines is a link.

Also, why numbering them? What does it mean? Is it needed?

2024-06-28 08:00 UTC, lemeurherve commented
Also, I would not mix #64 with this PR, or at least I would mention that this PR also includes this change.

2024-06-28 11:54 UTC, krisstern commented
I am not sure this is a good change either. It looks better and more consistent with the current design of https://www.jenkins.io/ before. 

@gounthar @Vandit1604 What do you think?

2024-06-28 12:02 UTC, gounthar commented
It was more pleasing to my terminal-nerd eyes, but that's not a good enough reason. 🥴

2024-06-28 12:11 UTC, Vandit1604 commented
I get the appeal what @shlomomdahan has in his mind, but this design has some problems like
1. If I visit the site for the 1st time, I won't figure out the buttons immediately. We can style the buttons like this to match the theme of jenkins.io. I think these will suit this site as well.
![image](https://github.com/jenkins-infra/stats.jenkins.io/assets/107131545/fc8ed9b9-c630-4b5d-b836-54bd0e9e3485)

2. We're using `monospace` font as the only font-family on the landing page. I would suggest using `georgia` font for **Jenkins Statistics** and using this font-family (got from devtool on jenkins.io) for the other text.
```
font-family: system-ui, "Segoe UI", roboto, "Noto Sans", oxygen, ubuntu, cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
``` 

WDYT @shlomomdahan @krisstern @gounthar

2024-06-28 14:52 UTC, shlomomdahan commented
Thoughts on the page with updated buttons?
![Screenshot 2024-06-28 at 10 52 16 AM](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/d5e8fd95-0684-477f-9569-fc61a3cbfcac)

![Screenshot 2024-06-28 at 10 52 28 AM](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/617cfc8a-d6db-47c6-ae3b-41dbc7fb5203)

2024-06-28 15:23 UTC, Vandit1604 commented
I would prefer the buttons to not have gradient, but that's my personal preference.
Also, White text on a Blue button has less visibility overall!

2024-06-28 16:28 UTC, lemeurherve commented
ICYDK, there is a general Jenkins Design Library that could be used for
inspiration: https://weekly.ci.jenkins.io/design-library

2024-06-29 04:17 UTC, krisstern commented
I don't think the buttons should have a color gradient according to our design library.

2024-06-30 11:07 UTC, krisstern requested changes
@shlomomdahan Could you please find out what font(s) they are using for [https://www.jenkins.io/](https://www.jenkins.io/) and use that for this website as well? 

Thanks!

2024-06-30 16:05 UTC, shlomomdahan commented
@krisstern 

![Screenshot 2024-06-30 at 12 03 53 PM](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/9c670fed-b242-41cd-8a1d-703218cb27b7)

here is comparison with font from Jenkins.io

My opinion is that monospace looks far better.


![Screenshot 2024-06-30 at 12 04 54 PM](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/05ec340f-b4e6-426b-9489-4def454965c6)

2024-06-30 16:09 UTC, krisstern commented
We understand you have a particular vision for this website, but we would like to make the font family consistent with the current design of [https://www.jenkins.io/](https://www.jenkins.io/) as in https://github.com/jenkins-infra/jenkins.io/blob/458cb120ef73721b3694fe9e52c41b552527aa70/content/stylesheets/core/_base.scss#L5

Please revise or we cannot approve it.

2024-06-30 16:10 UTC, krisstern commented
So the `font-family` field should really be:
```javascript
font-family: system-ui, "Segoe UI", roboto, "Noto Sans", oxygen, ubuntu, cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
```

2024-06-30 16:13 UTC, krisstern commented
I think for the blog we current have as the font-family: https://github.com/jenkins-infra/jenkins.io/blob/458cb120ef73721b3694fe9e52c41b552527aa70/content/stylesheets/pages/_blog.scss#L25

So basically you could do for the landing page something similar too.

2024-06-30 16:16 UTC, krisstern commented
> I get the appeal what @shlomomdahan has in his mind, but this design has some problems like
> 
> 1. If I visit the site for the 1st time, I won't figure out the buttons immediately. We can style the buttons like this to match the theme of jenkins.io. I think these will suit this site as well.
>    ![image](https://private-user-images.githubusercontent.com/107131545/344154888-fc8ed9b9-c630-4b5d-b836-54bd0e9e3485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjM5MTUsIm5iZiI6MTcxOTc2MzYxNSwicGF0aCI6Ii8xMDcxMzE1NDUvMzQ0MTU0ODg4LWZjOGVkOWI5LWM2MzAtNGI1ZC1iODM2LTU0YmQwZTllMzQ4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxNjA2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2U5NjQzMDM2ZDI2MzExZTA1ODFlMDgyMGVmNWM4OTlmN2ViYzNmYjI1ZWJmYmEwZWRmODVhNDI3OTY5NDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YZp65IYtU48_XHYWDk1eCfNo2zQGdgEDrEr5FADJiS8)
> 2. We're using `monospace` font as the only font-family on the landing page. I would suggest using `georgia` font for **Jenkins Statistics** and using this font-family (got from devtool on jenkins.io) for the other text.
> 
> ```
> font-family: system-ui, "Segoe UI", roboto, "Noto Sans", oxygen, ubuntu, cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
> ```
> 
> WDYT @shlomomdahan @krisstern @gounthar @lemeurherve

@Vandit1604 I don't think we are using maybe just `monospace` as the only font-family for the landing page. I see `Georgia` being used as well as least.

2024-06-30 16:19 UTC, krisstern commented
So in summary, maybe for the paragraph tags `<p>` (in our case the Material UI Typography equivalents) we should have `font-family: system-ui, "Segoe UI", roboto, "Noto Sans", oxygen, ubuntu, cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`, but for the headings tag like `<h1>` or their equivalents we should use `font-family: "Georgia", serif;`.

Hope this helps!

2024-06-30 16:21 UTC, shlomomdahan commented
@krisstern 

"font-family: system-ui results in Segoe on Windows, San Francisco on macOS, and Roboto on Android." - https://fonts.google.com/knowledge/glossary/system_font_web_safe_font

The font's are all relative to OS

Regardless, I think we should just close this PR then and revert back to how it was before (constant with the Jenkins.io site)

2024-06-30 16:25 UTC, krisstern commented
Yes, that is intentional. But I was not the one making that decision for the fonts used for [https://www.jenkins.io/](https://www.jenkins.io/). So please just follow the recommendation(s) that the mentoring team has come up with.

2024-06-30 16:26 UTC, krisstern commented
You will have to update the fonts now that we have come to a conclusion as your mentors.

2024-06-30 16:59 UTC, shlomomdahan commented
Font's have been updated. I will likewise update PR #64

2024-06-30 17:16 UTC, krisstern requested changes

2024-06-30 17:16 UTC, krisstern commented on src/pages/landing-page/index.tsx
> +                            <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
```suggestion
                            <Typography variant="h4" sx={{ fontFamily: 'Georgia, sarif', fontWeight: 'bold' }}>
```

2024-06-30 17:16 UTC, krisstern commented on src/pages/landing-page/index.tsx
> +                            <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
I think there was a bit of a misunderstanding here

2024-06-30 17:35 UTC, krisstern approved these changes

2024-06-30 17:35 UTC, merged