fix: cut build time in half by removing redundant import for plugin data
jenkins-infra/stats.jenkins.io pull request #91
Opened 2024-07-15 21:07 UTC by shlomomdahan

This PR cuts the build time in half.

There was a redundant import of the plugin versions data (~30mb) which this PR resolves.

While this does improve speed significantly, there are still further optimizations that should be made.

2024-07-15 22:44 UTC, krisstern requested changes

2024-07-15 22:44 UTC, krisstern commented on vite.config.ts
> +
```suggestion
```

2024-07-16 11:40 UTC, Vandit1604 approved these changes

2024-07-16 14:07 UTC, krisstern submitted a review, later dismissed

2024-07-16 14:18 UTC, krisstern commented
@gounthar Could you please review this PR for us?

2024-07-16 14:19 UTC, krisstern approved these changes

2024-07-16 14:24 UTC, krisstern commented
@shlomomdahan There seems to be some issues with this PR:
```shell
[2024-07-16T14:19:57.254Z] + npm run lint
[2024-07-16T14:19:57.556Z] 
[2024-07-16T14:19:57.556Z] > stats2.jenkins.io@0.0.0 lint
[2024-07-16T14:19:57.557Z] > eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
[2024-07-16T14:19:57.557Z] 
[2024-07-16T14:19:59.463Z] 
[2024-07-16T14:19:59.464Z] /home/jenkins/agent/workspace/Websites_stats_PR-91/src/hooks/useGetPluginVersionData.ts
[2024-07-16T14:19:59.464Z]   3:8  error  'rawPluginVersionData' is defined but never used  no-unused-vars
[2024-07-16T14:19:59.465Z]   3:8  error  'rawPluginVersionData' is defined but never used  @typescript-eslint/no-unused-vars
[2024-07-16T14:19:59.466Z] 
[2024-07-16T14:19:59.467Z] ✖ 2 problems (2 errors, 0 warnings)
[2024-07-16T14:19:59.468Z] 
```

2024-07-16 14:24 UTC, gounthar approved these changes
Looks good to me, thanks.

2024-07-16 15:16 UTC, krisstern approved these changes

2024-07-16 15:16 UTC, merged